json.id product.id
json.name product.name
json.category_id product.category_id
json.description product.description
json.price product.price
json.qoh product.qoh
json.user_id product.user_id
json.url image.product.id.url
json.user_name product.user.name